version: "3.9"

services:

  postgres:
    image: postgres:16
    container_name: zylo-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: zylo_erp
      POSTGRES_USER: zylo
      POSTGRES_PASSWORD: "123456"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zylo -d zylo_erp"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: zylo-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@zylo.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "5050:80"
    depends_on:
      - postgres

  api:
    build:
      context: ./erp-backend
      dockerfile: Dockerfile
    container_name: zylo-erp-api
    restart: "no"
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/zylo_erp
      SPRING_DATASOURCE_USERNAME: zylo
      SPRING_DATASOURCE_PASSWORD: "123456"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
