@echo off
echo [1/4] Parando containers antigos...
docker-compose down -v
echo [2/4] Removendo imagens antigas da API...
docker rmi zylo-erp-api
echo [3/4] Construindo nova imagem e subindo banco...
docker-compose up -d --build
echo [4/4] Aguardando API subir...
echo Acesse: http://localhost:8081/swagger-ui.html
pause