-- =====================================================
-- V002__CRIAR_TABELAS_USUARIOS.SQL
-- DESCRIÇÃO: ESTRUTURA COMPLETA DE USUÁRIOS, PERFIS E PERMISSÕES (RBAC)
-- AUTOR: BRENO OLIRVEIRA ALVES
-- DATA: 2025-01-10
-- =====================================================

-- =====================================================
-- TABELA: PERFIS (ROLES)
-- =====================================================
CREATE TABLE PERFIS (
                        CODIGO_PERFIL       BIGSERIAL PRIMARY KEY,
                        NOME_PERFIL         VARCHAR(50) UNIQUE NOT NULL,
                        DESCRICAO_PERFIL    TEXT,
                        SISTEMA             BOOLEAN DEFAULT FALSE NOT NULL,  -- SE TRUE, NÃO PODE SER EXCLUÍDO
                        CRIADO_EM           TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,

                        CONSTRAINT CHK_PERFIL_NOME_MINIMO CHECK (LENGTH(TRIM(NOME_PERFIL)) >= 3)
);

-- ÍNDICES
CREATE INDEX IDX_PERFIS_NOME ON PERFIS(NOME_PERFIL);
CREATE INDEX IDX_PERFIS_SISTEMA ON PERFIS(SISTEMA) WHERE SISTEMA = TRUE;

-- COMENTÁRIOS
COMMENT ON TABLE PERFIS IS
'PERFIS DE ACESSO (ROLES) DO SISTEMA - ADMIN, GESTOR, FINANCEIRO, OPERACIONAL';

COMMENT ON COLUMN PERFIS.SISTEMA IS
'INDICA SE É PERFIL DO SISTEMA (NÃO PODE SER EXCLUÍDO). ADMIN, GESTOR, ETC SÃO PERFIS DO SISTEMA.';

-- =====================================================
-- TABELA: PERMISSÕES
-- =====================================================
CREATE TABLE PERMISSOES (
                            CODIGO_PERMISSAO    BIGSERIAL PRIMARY KEY,
                            MODULO              VARCHAR(50) NOT NULL,  -- CLIENTES, CONTRATOS, OS, ETC
                            ACAO                VARCHAR(20) NOT NULL,  -- VER, CRIAR, EDITAR, EXCLUIR
                            DESCRICAO_PERMISSAO TEXT,

                            CONSTRAINT UK_PERMISSAO_MODULO_ACAO UNIQUE (MODULO, ACAO),
                            CONSTRAINT CHK_PERMISSAO_ACAO CHECK (ACAO IN ('VER', 'CRIAR', 'EDITAR', 'EXCLUIR'))
);

-- ÍNDICES
CREATE INDEX IDX_PERMISSOES_MODULO ON PERMISSOES(MODULO);
CREATE INDEX IDX_PERMISSOES_ACAO ON PERMISSOES(ACAO);

-- COMENTÁRIOS
COMMENT ON TABLE PERMISSOES IS
'PERMISSÕES GRANULARES DO SISTEMA - DEFINE AÇÕES POSSÍVEIS POR MÓDULO';

COMMENT ON COLUMN PERMISSOES.MODULO IS
'MÓDULO DO SISTEMA: CLIENTES, CONTRATOS, SERVICOS, OS, FATURAMENTO, USUARIOS';

COMMENT ON COLUMN PERMISSOES.ACAO IS
'AÇÃO PERMITIDA: VER (READ), CRIAR (CREATE), EDITAR (UPDATE), EXCLUIR (DELETE)';

-- =====================================================
-- TABELA: PERFIL_PERMISSÕES (N:N)
-- =====================================================
CREATE TABLE PERFIL_PERMISSOES (
                                   CODIGO_PERFIL       BIGINT NOT NULL,
                                   CODIGO_PERMISSAO    BIGINT NOT NULL,

                                   PRIMARY KEY (CODIGO_PERFIL, CODIGO_PERMISSAO),

                                   CONSTRAINT FK_PERFIL_PERMISSOES_PERFIL
                                       FOREIGN KEY (CODIGO_PERFIL)
                                           REFERENCES PERFIS(CODIGO_PERFIL)
                                           ON DELETE CASCADE,

                                   CONSTRAINT FK_PERFIL_PERMISSOES_PERMISSAO
                                       FOREIGN KEY (CODIGO_PERMISSAO)
                                           REFERENCES PERMISSOES(CODIGO_PERMISSAO)
                                           ON DELETE CASCADE
);

-- ÍNDICES PARA OTIMIZAR JOINS
CREATE INDEX IDX_PERFIL_PERMISSOES_PERFIL ON PERFIL_PERMISSOES(CODIGO_PERFIL);
CREATE INDEX IDX_PERFIL_PERMISSOES_PERMISSAO ON PERFIL_PERMISSOES(CODIGO_PERMISSAO);

COMMENT ON TABLE PERFIL_PERMISSOES IS
'TABELA ASSOCIATIVA ENTRE PERFIS E PERMISSÕES - DEFINE QUAIS PERMISSÕES CADA PERFIL POSSUI';

-- =====================================================
-- TABELA: USUÁRIOS
-- =====================================================
CREATE TABLE USUARIOS (
                          CODIGO_USUARIO      BIGSERIAL PRIMARY KEY,
                          NOME_COMPLETO       VARCHAR(100) NOT NULL,
                          EMAIL               VARCHAR(100) UNIQUE NOT NULL,
                          SENHA_HASH          VARCHAR(255) NOT NULL,  -- BCRYPT HASH
                          CODIGO_PERFIL       BIGINT NOT NULL,
                          ATIVO               BOOLEAN DEFAULT TRUE NOT NULL,

    -- AUDITORIA
                          CRIADO_EM           TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
                          CRIADO_POR          BIGINT NOT NULL,
                          ATUALIZADO_EM       TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
                          ATUALIZADO_POR      BIGINT NOT NULL,
                          EXCLUIDO_EM         TIMESTAMP WITH TIME ZONE,
                          EXCLUIDO_POR        BIGINT NOT NULL,

    -- CONSTRAINTS
                          CONSTRAINT FK_USUARIOS_PERFIL
                              FOREIGN KEY (CODIGO_PERFIL)
                                  REFERENCES PERFIS(CODIGO_PERFIL)
                                  ON DELETE RESTRICT,  -- NÃO PERMITE EXCLUIR PERFIL SE HOUVER USUÁRIOS

                          CONSTRAINT FK_USUARIOS_EXCLUIDO_POR
                              FOREIGN KEY (EXCLUIDO_POR)
                                  REFERENCES USUARIOS(CODIGO_USUARIO)
                                  ON DELETE SET NULL,

                          CONSTRAINT CHK_USUARIO_NOME_MINIMO CHECK (LENGTH(TRIM(NOME_COMPLETO)) >= 3),
                          CONSTRAINT CHK_USUARIO_EMAIL_FORMATO CHECK (EMAIL ~* '^[A-ZA-Z0-9._%+-]+@[A-ZA-Z0-9.-]+\.[A-ZA-Z]{2,}$'),
    CONSTRAINT CHK_USUARIO_EXCLUIDO_LOGICA CHECK (
        (EXCLUIDO_EM IS NULL AND EXCLUIDO_POR IS NULL) OR
        (EXCLUIDO_EM IS NOT NULL AND EXCLUIDO_POR IS NOT NULL)
    )
);

-- ÍNDICES ESTRATÉGICOS
CREATE UNIQUE INDEX IDX_USUARIOS_EMAIL_ATIVO
    ON USUARIOS(LOWER(EMAIL))
    WHERE EXCLUIDO_EM IS NULL;  -- EMAIL ÚNICO APENAS ENTRE USUÁRIOS ATIVOS

CREATE INDEX IDX_USUARIOS_PERFIL ON USUARIOS(CODIGO_PERFIL);
CREATE INDEX IDX_USUARIOS_ATIVO ON USUARIOS(ATIVO) WHERE ATIVO = TRUE;
CREATE INDEX IDX_USUARIOS_NOME ON USUARIOS(NOME_COMPLETO);
CREATE INDEX IDX_USUARIOS_EXCLUIDO ON USUARIOS(EXCLUIDO_EM) WHERE EXCLUIDO_EM IS NOT NULL;

-- COMENTÁRIOS
COMMENT ON TABLE USUARIOS IS
'USUÁRIOS DO SISTEMA - PESSOAS COM ACESSO AO ERP';

COMMENT ON COLUMN USUARIOS.SENHA_HASH IS
'HASH BCRYPT DA SENHA (NUNCA ARMAZENAR SENHA EM TEXTO PLANO)';

COMMENT ON COLUMN USUARIOS.ATIVO IS
'INDICA SE USUÁRIO PODE FAZER LOGIN (DIFERENTE DE EXCLUÍDO)';

COMMENT ON COLUMN USUARIOS.EXCLUIDO_EM IS
'DATA/HORA DE EXCLUSÃO LÓGICA (SOFT DELETE). NULL = NÃO EXCLUÍDO';

-- =====================================================
-- TABELA: HISTÓRICO DE ACESSOS (LOGIN LOGS)
-- =====================================================
CREATE TABLE HISTORICO_ACESSOS (
                                   CODIGO_ACESSO       BIGSERIAL PRIMARY KEY,
                                   CODIGO_USUARIO      BIGINT NOT NULL,
                                   IP_ACESSO           VARCHAR(45),  -- SUPORTA IPV6
                                   USER_AGENT          TEXT,  -- INFORMAÇÕES DO NAVEGADOR
                                   DATA_HORA_ACESSO    TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                   SUCESSO             BOOLEAN DEFAULT TRUE NOT NULL,
                                   MOTIVO_FALHA        VARCHAR(255),  -- SENHA INCORRETA, USUÁRIO INATIVO, ETC

                                   CONSTRAINT FK_HISTORICO_ACESSOS_USUARIO
                                       FOREIGN KEY (CODIGO_USUARIO)
                                           REFERENCES USUARIOS(CODIGO_USUARIO)
                                           ON DELETE CASCADE
);

-- ÍNDICES PARA CONSULTAS COMUNS
CREATE INDEX IDX_HISTORICO_USUARIO ON HISTORICO_ACESSOS(CODIGO_USUARIO);
CREATE INDEX IDX_HISTORICO_DATA ON HISTORICO_ACESSOS(DATA_HORA_ACESSO DESC);
CREATE INDEX IDX_HISTORICO_SUCESSO ON HISTORICO_ACESSOS(SUCESSO) WHERE SUCESSO = FALSE;
CREATE INDEX IDX_HISTORICO_IP ON HISTORICO_ACESSOS(IP_ACESSO);

-- ÍNDICE COMPOSTO PARA "ÚLTIMOS ACESSOS DO USUÁRIO"
CREATE INDEX IDX_HISTORICO_USUARIO_DATA ON HISTORICO_ACESSOS(CODIGO_USUARIO, DATA_HORA_ACESSO DESC);

COMMENT ON TABLE HISTORICO_ACESSOS IS
'REGISTRO DE TODAS AS TENTATIVAS DE LOGIN (BEM-SUCEDIDAS OU NÃO)';

COMMENT ON COLUMN HISTORICO_ACESSOS.SUCESSO IS
'TRUE = LOGIN BEM-SUCEDIDO, FALSE = FALHA (SENHA INCORRETA, USUÁRIO BLOQUEADO, ETC)';

-- =====================================================
-- TRIGGERS: ATUALIZAÇÃO AUTOMÁTICA DE TIMESTAMPS
-- =====================================================
CREATE TRIGGER TRG_USUARIOS_ATUALIZAR_TIMESTAMP
    BEFORE UPDATE ON USUARIOS
    FOR EACH ROW
    EXECUTE FUNCTION ATUALIZAR_TIMESTAMP_ATUALIZACAO();

-- =====================================================
-- TRIGGERS: AUDITORIA (REGISTRA MUDANÇAS CRÍTICAS)
-- =====================================================
-- NOTA: A FUNÇÃO REGISTRAR_AUDITORIA() PRECISA SER ADAPTADA PARA CADA TABELA
-- POR CAUSA DO NOME DA PK. VOU CRIAR TRIGGERS ESPECÍFICOS DEPOIS.

-- =====================================================
-- ÍNDICES ADICIONAIS PARA PERFORMANCE
-- =====================================================

-- ÍNDICE PARCIAL: APENAS USUÁRIOS ATIVOS E NÃO EXCLUÍDOS
CREATE INDEX IDX_USUARIOS_ATIVOS_COMPLETO
    ON USUARIOS(CODIGO_USUARIO, NOME_COMPLETO, EMAIL)
    WHERE ATIVO = TRUE AND EXCLUIDO_EM IS NULL;

-- ÍNDICE PARA BUSCA CASE-INSENSITIVE POR NOME
CREATE INDEX IDX_USUARIOS_NOME_LOWER ON USUARIOS(LOWER(NOME_COMPLETO));

-- =====================================================
-- CONSTRAINTS ADICIONAIS DE SEGURANÇA
-- =====================================================

-- IMPEDE QUE O ÚLTIMO ADMIN SEJA DESATIVADO
-- (SERÁ IMPLEMENTADO VIA TRIGGER OU LÓGICA DE APLICAÇÃO)

-- =====================================================
-- FIM DA MIGRATION V002
-- =====================================================