-- =====================================================
-- V004__CRIAR_TABELAS_SERVICOS_CONTRATOS.SQL
-- DESCRIÇÃO: CATÁLOGO DE SERVIÇOS E GESTÃO DE CONTRATOS
-- AUTOR: ERP PORTAL TEAM
-- DATA: 2025-01-10
-- =====================================================

-- =====================================================
-- TABELA: SERVIÇOS (CATÁLOGO)
-- =====================================================
CREATE TABLE SERVICOS (
                          CODIGO_SERVICO          BIGSERIAL PRIMARY KEY,

    -- IDENTIFICAÇÃO
                          NOME_SERVICO            VARCHAR(200) NOT NULL,
                          DESCRICAO_SERVICO       TEXT,

    -- PRECIFICAÇÃO
                          TIPO_COBRANCA           VARCHAR(30) NOT NULL,
                          VALOR_BASE              NUMERIC(10,2) NOT NULL,  -- VALOR PADRÃO (PODE SER ALTERADO NO CONTRATO)

    -- SLA
                          SLA_HORAS               INTEGER,  -- SLA PADRÃO EM HORAS

    -- CATEGORIZAÇÃO
                          CATEGORIA               VARCHAR(50),

    -- STATUS
                          ATIVO                   BOOLEAN DEFAULT TRUE NOT NULL,

    -- AUDITORIA
                          CRIADO_EM               TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
                          ATUALIZADO_EM           TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,

    -- CONSTRAINTS
                          CONSTRAINT CHK_SERVICO_TIPO_COBRANCA CHECK (
                              TIPO_COBRANCA IN ('MENSALIDADE', 'PROJETO_FECHADO', 'HORAS_CONTRATADAS', 'SOB_DEMANDA')
                              ),

                          CONSTRAINT CHK_SERVICO_CATEGORIA CHECK (
                              CATEGORIA IS NULL OR CATEGORIA IN ('DESENVOLVIMENTO', 'SUPORTE', 'CONSULTORIA', 'INFRAESTRUTURA')
                              ),

                          CONSTRAINT CHK_SERVICO_VALOR_POSITIVO CHECK (VALOR_BASE >= 0),

                          CONSTRAINT CHK_SERVICO_SLA_POSITIVO CHECK (SLA_HORAS IS NULL OR SLA_HORAS > 0),

                          CONSTRAINT CHK_SERVICO_NOME_MINIMO CHECK (LENGTH(TRIM(NOME_SERVICO)) >= 3)
);

-- =====================================================
-- ÍNDICES - SERVIÇOS
-- =====================================================
CREATE INDEX IDX_SERVICOS_ATIVO ON SERVICOS(ATIVO) WHERE ATIVO = TRUE;
CREATE INDEX IDX_SERVICOS_CATEGORIA ON SERVICOS(CATEGORIA);
CREATE INDEX IDX_SERVICOS_TIPO_COBRANCA ON SERVICOS(TIPO_COBRANCA);
CREATE INDEX IDX_SERVICOS_NOME_LOWER ON SERVICOS(LOWER(NOME_SERVICO));

-- ÍNDICE PARA LISTAGEM PADRÃO (ATIVOS ORDENADOS POR NOME)
CREATE INDEX IDX_SERVICOS_LISTAGEM ON SERVICOS(ATIVO, NOME_SERVICO) WHERE ATIVO = TRUE;

COMMENT ON TABLE SERVICOS IS
'CATÁLOGO DE SERVIÇOS OFERECIDOS PELA SOFTWARE HOUSE';

COMMENT ON COLUMN SERVICOS.TIPO_COBRANCA IS
'MENSALIDADE: RECORRENTE MENSAL | PROJETO_FECHADO: VALOR FIXO | HORAS_CONTRATADAS: POR HORA | SOB_DEMANDA: NÃO RECORRENTE';

COMMENT ON COLUMN SERVICOS.VALOR_BASE IS
'VALOR PADRÃO DO SERVIÇO. PODE SER CUSTOMIZADO NO CONTRATO.';

-- =====================================================
-- TABELA: CONTRATOS
-- =====================================================
CREATE TABLE CONTRATOS (
                           CODIGO_CONTRATO         BIGSERIAL PRIMARY KEY,

    -- IDENTIFICAÇÃO
                           NUMERO_CONTRATO         VARCHAR(20) UNIQUE NOT NULL,  -- GERADO: CT-2025-000001
                           CODIGO_CLIENTE          BIGINT NOT NULL,

    -- TIPO E VALOR
                           TIPO_CONTRATO           VARCHAR(30) NOT NULL,
                           VALOR_TOTAL             NUMERIC(10,2) NOT NULL,

    -- VIGÊNCIA
                           DATA_INICIO             DATE NOT NULL,
                           DATA_FIM                DATE NOT NULL,
                           DURACAO_MESES           INTEGER,  -- PARA CONTRATOS MENSAIS

    -- SLA
                           SLA_HORAS               INTEGER,  -- SOBRESCREVE SLA DOS SERVIÇOS SE DEFINIDO

    -- STATUS
                           STATUS_CONTRATO         VARCHAR(20) DEFAULT 'ATIVO' NOT NULL,

    -- OBSERVAÇÕES
                           OBSERVACOES             TEXT,

    -- AUDITORIA COMPLETA
                           CRIADO_EM               TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
                           CRIADO_POR              BIGINT NOT NULL,
                           ATUALIZADO_EM           TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
                           ATUALIZADO_POR          BIGINT NOT NULL,
                           EXCLUIDO_EM             TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
                           EXCLUIDO_POR            BIGINT NOT NULL,

    -- FOREIGN KEYS
                           CONSTRAINT FK_CONTRATOS_CLIENTE
                               FOREIGN KEY (CODIGO_CLIENTE)
                                   REFERENCES CLIENTES(CODIGO_CLIENTE)
                                   ON DELETE RESTRICT,  -- NÃO PERMITE EXCLUIR CLIENTE COM CONTRATOS

                           CONSTRAINT FK_CONTRATOS_CRIADO_POR
                               FOREIGN KEY (CRIADO_POR)
                                   REFERENCES USUARIOS(CODIGO_USUARIO)
                                   ON DELETE RESTRICT,

                           CONSTRAINT FK_CONTRATOS_ATUALIZADO_POR
                               FOREIGN KEY (ATUALIZADO_POR)
                                   REFERENCES USUARIOS(CODIGO_USUARIO)
                                   ON DELETE RESTRICT,

    -- CONSTRAINTS DE VALIDAÇÃO
                           CONSTRAINT CHK_CONTRATO_TIPO CHECK (
                               TIPO_CONTRATO IN ('MENSALIDADE', 'PROJETO_FECHADO', 'HORAS_CONTRATADAS')
                               ),

                           CONSTRAINT CHK_CONTRATO_STATUS CHECK (
                               STATUS_CONTRATO IN ('ATIVO', 'SUSPENSO', 'ENCERRADO', 'CANCELADO')
                               ),

                           CONSTRAINT CHK_CONTRATO_VALOR_POSITIVO CHECK (VALOR_TOTAL >= 0),

                           CONSTRAINT CHK_CONTRATO_DATAS CHECK (DATA_FIM >= DATA_INICIO),

                           CONSTRAINT CHK_CONTRATO_DURACAO_POSITIVA CHECK (
                               DURACAO_MESES IS NULL OR DURACAO_MESES > 0
                               ),

                           CONSTRAINT CHK_CONTRATO_SLA_POSITIVO CHECK (
                               SLA_HORAS IS NULL OR SLA_HORAS > 0
                               )
);

-- =====================================================
-- ÍNDICES - CONTRATOS
-- =====================================================
CREATE UNIQUE INDEX IDX_CONTRATOS_NUMERO ON CONTRATOS(NUMERO_CONTRATO);
CREATE INDEX IDX_CONTRATOS_CLIENTE ON CONTRATOS(CODIGO_CLIENTE);
CREATE INDEX IDX_CONTRATOS_STATUS ON CONTRATOS(STATUS_CONTRATO);
CREATE INDEX IDX_CONTRATOS_VIGENCIA ON CONTRATOS(DATA_INICIO, DATA_FIM);
CREATE INDEX IDX_CONTRATOS_TIPO ON CONTRATOS(TIPO_CONTRATO);

-- ÍNDICE PARA CONTRATOS ATIVOS DE UM CLIENTE
CREATE INDEX IDX_CONTRATOS_CLIENTE_ATIVO
    ON CONTRATOS(CODIGO_CLIENTE, STATUS_CONTRATO)
    WHERE STATUS_CONTRATO = 'ATIVO';

-- ÍNDICE PARA CONTRATOS QUE VENCEM EM BREVE
CREATE INDEX IDX_CONTRATOS_VENCIMENTO
    ON CONTRATOS(DATA_FIM)
    WHERE STATUS_CONTRATO = 'ATIVO';

-- ÍNDICE PARA AUDITORIA
CREATE INDEX IDX_CONTRATOS_AUDITORIA ON CONTRATOS(CRIADO_POR, ATUALIZADO_POR);

COMMENT ON TABLE CONTRATOS IS
'CONTRATOS FIRMADOS COM CLIENTES (MENSALIDADES, PROJETOS, HORAS CONTRATADAS)';

COMMENT ON COLUMN CONTRATOS.NUMERO_CONTRATO IS
'NÚMERO ÚNICO DO CONTRATO NO FORMATO CT-2025-000001 (GERADO AUTOMATICAMENTE)';

COMMENT ON COLUMN CONTRATOS.STATUS_CONTRATO IS
'ATIVO: EM VIGÊNCIA | SUSPENSO: PAUSADO TEMPORARIAMENTE | ENCERRADO: FINALIZADO NATURALMENTE | CANCELADO: ENCERRADO ANTES DO PRAZO';

-- =====================================================
-- TABELA: CONTRATO_SERVICOS (N:N COM VALORES CUSTOMIZADOS)
-- =====================================================
CREATE TABLE CONTRATO_SERVICOS (
                                   CODIGO_CONTRATO_SERVICO BIGSERIAL PRIMARY KEY,
                                   CODIGO_CONTRATO         BIGINT NOT NULL,
                                   CODIGO_SERVICO          BIGINT NOT NULL,

    -- VALOR CUSTOMIZADO (PODE SER DIFERENTE DO VALOR_BASE DO SERVIÇO)
                                   VALOR_SERVICO           NUMERIC(10,2) NOT NULL,
                                   QUANTIDADE              INTEGER DEFAULT 1 NOT NULL,

    -- FOREIGN KEYS
                                   CONSTRAINT FK_CONTRATO_SERVICOS_CONTRATO
                                       FOREIGN KEY (CODIGO_CONTRATO)
                                           REFERENCES CONTRATOS(CODIGO_CONTRATO)
                                           ON DELETE CASCADE,  -- SE CONTRATO É EXCLUÍDO, SERVIÇOS VINCULADOS TAMBÉM

                                   CONSTRAINT FK_CONTRATO_SERVICOS_SERVICO
                                       FOREIGN KEY (CODIGO_SERVICO)
                                           REFERENCES SERVICOS(CODIGO_SERVICO)
                                           ON DELETE RESTRICT,  -- NÃO PERMITE EXCLUIR SERVIÇO VINCULADO A CONTRATO

    -- CONSTRAINTS
                                   CONSTRAINT UK_CONTRATO_SERVICO UNIQUE (CODIGO_CONTRATO, CODIGO_SERVICO),

                                   CONSTRAINT CHK_CONTRATO_SERVICO_VALOR_POSITIVO CHECK (VALOR_SERVICO >= 0),

                                   CONSTRAINT CHK_CONTRATO_SERVICO_QUANTIDADE_POSITIVA CHECK (QUANTIDADE > 0)
);

-- =====================================================
-- ÍNDICES - CONTRATO SERVICOS
-- =====================================================
CREATE INDEX IDX_CONTRATO_SERVICOS_CONTRATO ON CONTRATO_SERVICOS(CODIGO_CONTRATO);
CREATE INDEX IDX_CONTRATO_SERVICOS_SERVICO ON CONTRATO_SERVICOS(CODIGO_SERVICO);

COMMENT ON TABLE CONTRATO_SERVICOS IS
'SERVIÇOS INCLUSOS EM CADA CONTRATO (COM VALORES CUSTOMIZADOS POR CONTRATO)';

COMMENT ON COLUMN CONTRATO_SERVICOS.VALOR_SERVICO IS
'VALOR DO SERVIÇO NESTE CONTRATO (PODE SER DIFERENTE DO VALOR_BASE DO CATÁLOGO)';

COMMENT ON COLUMN CONTRATO_SERVICOS.QUANTIDADE IS
'QUANTIDADE DE UNIDADES (ÚTIL PARA "HORAS CONTRATADAS", "LICENÇAS", ETC)';

-- =====================================================
-- TABELA: HISTÓRICO DE CONTRATOS (AUDITORIA)
-- =====================================================
CREATE TABLE HISTORICO_CONTRATOS (
                                     CODIGO_HISTORICO        BIGSERIAL PRIMARY KEY,
                                     CODIGO_CONTRATO         BIGINT NOT NULL,

    -- TIPO DE ALTERAÇÃO
                                     TIPO_ALTERACAO          VARCHAR(50) NOT NULL,
                                     DESCRICAO_ALTERACAO     TEXT,

    -- QUEM E QUANDO
                                     CODIGO_USUARIO          BIGINT,
                                     DATA_HORA_ALTERACAO     TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,

    -- FOREIGN KEYS
                                     CONSTRAINT FK_HISTORICO_CONTRATO
                                         FOREIGN KEY (CODIGO_CONTRATO)
                                             REFERENCES CONTRATOS(CODIGO_CONTRATO)
                                             ON DELETE CASCADE,

                                     CONSTRAINT FK_HISTORICO_USUARIO
                                         FOREIGN KEY (CODIGO_USUARIO)
                                             REFERENCES USUARIOS(CODIGO_USUARIO)
                                             ON DELETE SET NULL,

    -- CONSTRAINTS
                                     CONSTRAINT CHK_HISTORICO_TIPO_ALTERACAO CHECK (
                                         TIPO_ALTERACAO IN (
                                                            'CRIACAO', 'EDICAO_VALOR', 'ADICAO_SERVICO', 'REMOCAO_SERVICO',
                                                            'SUSPENSAO', 'REATIVACAO', 'ENCERRAMENTO', 'CANCELAMENTO', 'RENOVACAO'
                                             )
                                         )
);

-- =====================================================
-- ÍNDICES - HISTÓRICO CONTRATOS
-- =====================================================
CREATE INDEX IDX_HISTORICO_CONTRATOS_CONTRATO
    ON HISTORICO_CONTRATOS(CODIGO_CONTRATO, DATA_HORA_ALTERACAO DESC);
CREATE INDEX IDX_HISTORICO_CONTRATOS_USUARIO ON HISTORICO_CONTRATOS(CODIGO_USUARIO);
CREATE INDEX IDX_HISTORICO_CONTRATOS_TIPO ON HISTORICO_CONTRATOS(TIPO_ALTERACAO);

COMMENT ON TABLE HISTORICO_CONTRATOS IS
'HISTÓRICO DE TODAS AS ALTERAÇÕES REALIZADAS EM CONTRATOS (RASTREABILIDADE COMPLETA)';

-- =====================================================
-- TRIGGERS: ATUALIZAÇÃO AUTOMÁTICA DE TIMESTAMPS
-- =====================================================
CREATE TRIGGER TRG_SERVICOS_ATUALIZAR_TIMESTAMP
    BEFORE UPDATE ON SERVICOS
    FOR EACH ROW
    EXECUTE FUNCTION ATUALIZAR_TIMESTAMP_ATUALIZACAO();

CREATE TRIGGER TRG_CONTRATOS_ATUALIZAR_TIMESTAMP
    BEFORE UPDATE ON CONTRATOS
    FOR EACH ROW
    EXECUTE FUNCTION ATUALIZAR_TIMESTAMP_ATUALIZACAO();

-- =====================================================
-- TRIGGER: GERAR NÚMERO DO CONTRATO AUTOMATICAMENTE
-- =====================================================
CREATE OR REPLACE FUNCTION GERAR_NUMERO_CONTRATO()
RETURNS TRIGGER AS $$
BEGIN
    -- SE NÚMERO NÃO FOI FORNECIDO, GERA AUTOMATICAMENTE
    IF NEW.NUMERO_CONTRATO IS NULL OR NEW.NUMERO_CONTRATO = '' THEN
        NEW.NUMERO_CONTRATO := GERAR_NUMERO_SEQUENCIAL('CT', 'SEQ_NUMERO_CONTRATO', 6);
END IF;

RETURN NEW;
END;
$$ LANGUAGE PLPGSQL;

CREATE TRIGGER TRG_CONTRATOS_GERAR_NUMERO
    BEFORE INSERT ON CONTRATOS
    FOR EACH ROW
    EXECUTE FUNCTION GERAR_NUMERO_CONTRATO();

COMMENT ON FUNCTION GERAR_NUMERO_CONTRATO() IS
'GERA NÚMERO DO CONTRATO AUTOMATICAMENTE NO FORMATO CT-2025-000001';

-- =====================================================
-- TRIGGER: RECALCULAR VALOR TOTAL DO CONTRATO AO MUDAR SERVIÇOS
-- =====================================================
CREATE OR REPLACE FUNCTION RECALCULAR_VALOR_TOTAL_CONTRATO()
RETURNS TRIGGER AS $$
DECLARE
NOVO_VALOR_TOTAL NUMERIC(10,2);
BEGIN
    -- CALCULA O VALOR TOTAL BASEADO NOS SERVIÇOS VINCULADOS
SELECT COALESCE(SUM(VALOR_SERVICO * QUANTIDADE), 0)
INTO NOVO_VALOR_TOTAL
FROM CONTRATO_SERVICOS
WHERE CODIGO_CONTRATO = COALESCE(NEW.CODIGO_CONTRATO, OLD.CODIGO_CONTRATO);

-- ATUALIZA O VALOR TOTAL DO CONTRATO
UPDATE CONTRATOS
SET VALOR_TOTAL = NOVO_VALOR_TOTAL,
    ATUALIZADO_EM = CURRENT_TIMESTAMP
WHERE CODIGO_CONTRATO = COALESCE(NEW.CODIGO_CONTRATO, OLD.CODIGO_CONTRATO);

RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE PLPGSQL;

CREATE TRIGGER TRG_CONTRATO_SERVICOS_RECALCULAR_VALOR_INSERT
    AFTER INSERT ON CONTRATO_SERVICOS
    FOR EACH ROW
    EXECUTE FUNCTION RECALCULAR_VALOR_TOTAL_CONTRATO();

CREATE TRIGGER TRG_CONTRATO_SERVICOS_RECALCULAR_VALOR_UPDATE
    AFTER UPDATE ON CONTRATO_SERVICOS
    FOR EACH ROW
    EXECUTE FUNCTION RECALCULAR_VALOR_TOTAL_CONTRATO();

CREATE TRIGGER TRG_CONTRATO_SERVICOS_RECALCULAR_VALOR_DELETE
    AFTER DELETE ON CONTRATO_SERVICOS
    FOR EACH ROW
    EXECUTE FUNCTION RECALCULAR_VALOR_TOTAL_CONTRATO();

COMMENT ON FUNCTION RECALCULAR_VALOR_TOTAL_CONTRATO() IS
'RECALCULA AUTOMATICAMENTE O VALOR_TOTAL DO CONTRATO QUANDO SERVIÇOS SÃO ADICIONADOS/REMOVIDOS/ALTERADOS';

-- =====================================================
-- TRIGGER: REGISTRAR MUDANÇAS NO HISTÓRICO DE CONTRATOS
-- =====================================================
CREATE OR REPLACE FUNCTION REGISTRAR_HISTORICO_CONTRATO()
RETURNS TRIGGER AS $$
DECLARE
TIPO_MUDANCA VARCHAR(50);
    DESCRICAO TEXT;
    CODIGO_USUARIO_ATUAL BIGINT;
BEGIN
    -- TENTA PEGAR O CÓDIGO DO USUÁRIO DA SESSÃO
BEGIN
        CODIGO_USUARIO_ATUAL := CURRENT_SETTING('APP.CODIGO_USUARIO', TRUE)::BIGINT;
EXCEPTION WHEN OTHERS THEN
        CODIGO_USUARIO_ATUAL := NULL;
END;

    -- INSERT = CRIAÇÃO
    IF (TG_OP = 'INSERT') THEN
        TIPO_MUDANCA := 'CRIACAO';
        DESCRICAO := 'CONTRATO CRIADO COM VALOR TOTAL DE R$ ' || NEW.VALOR_TOTAL;

    -- UPDATE = DETECTAR TIPO DE MUDANÇA
    ELSIF (TG_OP = 'UPDATE') THEN
        -- MUDANÇA DE STATUS
        IF OLD.STATUS_CONTRATO != NEW.STATUS_CONTRATO THEN
            CASE NEW.STATUS_CONTRATO
                WHEN 'SUSPENSO' THEN
                    TIPO_MUDANCA := 'SUSPENSAO';
                    DESCRICAO := 'CONTRATO SUSPENSO';
WHEN 'ATIVO' THEN
                    TIPO_MUDANCA := 'REATIVACAO';
                    DESCRICAO := 'CONTRATO REATIVADO';
WHEN 'ENCERRADO' THEN
                    TIPO_MUDANCA := 'ENCERRAMENTO';
                    DESCRICAO := 'CONTRATO ENCERRADO';
WHEN 'CANCELADO' THEN
                    TIPO_MUDANCA := 'CANCELAMENTO';
                    DESCRICAO := 'CONTRATO CANCELADO';
END CASE;

        -- MUDANÇA DE VALOR
        ELSIF OLD.VALOR_TOTAL != NEW.VALOR_TOTAL THEN
            TIPO_MUDANCA := 'EDICAO_VALOR';
            DESCRICAO := 'VALOR ALTERADO DE R$ ' || OLD.VALOR_TOTAL || ' PARA R$ ' || NEW.VALOR_TOTAL;

        -- OUTRAS MUDANÇAS
ELSE
            RETURN NEW;  -- NÃO REGISTRA MUDANÇAS NÃO CRÍTICAS
END IF;

ELSE
        RETURN NEW;
END IF;

    -- INSERE NO HISTÓRICO
INSERT INTO HISTORICO_CONTRATOS (
    CODIGO_CONTRATO,
    TIPO_ALTERACAO,
    DESCRICAO_ALTERACAO,
    CODIGO_USUARIO
) VALUES (
             NEW.CODIGO_CONTRATO,
             TIPO_MUDANCA,
             DESCRICAO,
             CODIGO_USUARIO_ATUAL
         );

RETURN NEW;
END;
$$ LANGUAGE PLPGSQL;

CREATE TRIGGER TRG_CONTRATOS_HISTORICO
    AFTER INSERT OR UPDATE ON CONTRATOS
                        FOR EACH ROW
                        EXECUTE FUNCTION REGISTRAR_HISTORICO_CONTRATO();

COMMENT ON FUNCTION REGISTRAR_HISTORICO_CONTRATO() IS
'REGISTRA AUTOMATICAMENTE ALTERAÇÕES CRÍTICAS NO HISTÓRICO DE CONTRATOS';

-- =====================================================
-- TRIGGER: ENCERRAR AUTOMATICAMENTE CONTRATOS VENCIDOS
-- =====================================================
-- NOTA: ESTE TRIGGER SERIA EXECUTADO POR UM JOB DIÁRIO, NÃO EM CADA OPERAÇÃO
-- POR QUESTÃO DE PERFORMANCE, ISSO SERÁ IMPLEMENTADO NO BACKEND

-- =====================================================
-- VIEWS ÚTEIS
-- =====================================================

-- VIEW: CONTRATOS ATIVOS COM CLIENTE E VALOR
CREATE OR REPLACE VIEW VW_CONTRATOS_ATIVOS AS
SELECT
    CT.CODIGO_CONTRATO,
    CT.NUMERO_CONTRATO,
    CL.CODIGO_CLIENTE,
    CL.RAZAO_SOCIAL,
    CL.NOME_FANTASIA,
    CT.TIPO_CONTRATO,
    CT.VALOR_TOTAL,
    CT.DATA_INICIO,
    CT.DATA_FIM,
    CT.STATUS_CONTRATO,
    -- DIAS ATÉ VENCIMENTO
    (CT.DATA_FIM - CURRENT_DATE) AS DIAS_ATE_VENCIMENTO,
    -- TOTAL DE SERVIÇOS
    (SELECT COUNT(*) FROM CONTRATO_SERVICOS CS WHERE CS.CODIGO_CONTRATO = CT.CODIGO_CONTRATO) AS TOTAL_SERVICOS
FROM CONTRATOS CT
         INNER JOIN CLIENTES CL ON CT.CODIGO_CLIENTE = CL.CODIGO_CLIENTE
WHERE CT.STATUS_CONTRATO = 'ATIVO'
  AND CL.EXCLUIDO_EM IS NULL
ORDER BY CT.DATA_FIM ASC;

COMMENT ON VIEW VW_CONTRATOS_ATIVOS IS
'VISÃO DE CONTRATOS ATIVOS COM INFORMAÇÕES DO CLIENTE E DIAS ATÉ VENCIMENTO';

-- =====================================================
-- FIM DA MIGRATION V004
-- =====================================================