-- ORDENS DE SERVIÇO
CREATE TABLE ORDENS_SERVICO (
                                CODIGO_OS BIGSERIAL PRIMARY KEY,
                                NUMERO_OS VARCHAR(20) UNIQUE NOT NULL,  -- OS-2025-000001
                                CODIGO_CLIENTE BIGINT NOT NULL,
                                CODIGO_CONTRATO BIGINT NOT NULL,
                                CODIGO_SERVICO BIGINT NOT NULL,
                                TITULO_OS VARCHAR(200) NOT NULL,
                                DESCRICAO_OS TEXT,
                                PRIORIDADE VARCHAR(20) DEFAULT 'NORMAL' NOT NULL,
                                STATUS_OS VARCHAR(30) DEFAULT 'ABERTA' NOT NULL,
                                CODIGO_RESPONSAVEL BIGINT,
                                SLA_HORAS INTEGER,
                                DATA_ABERTURA TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                DATA_LIMITE TIMESTAMP WITH TIME ZONE,
                                DATA_FINALIZACAO TIMESTAMP WITH TIME ZONE,
                                CRIADO_EM TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                CRIADO_POR BIGINT NOT NULL,

                                CONSTRAINT FK_OS_CLIENTE FOREIGN KEY (CODIGO_CLIENTE) REFERENCES CLIENTES(CODIGO_CLIENTE) ON DELETE RESTRICT,
                                CONSTRAINT FK_OS_CONTRATO FOREIGN KEY (CODIGO_CONTRATO) REFERENCES CONTRATOS(CODIGO_CONTRATO) ON DELETE RESTRICT,
                                CONSTRAINT FK_OS_SERVICO FOREIGN KEY (CODIGO_SERVICO) REFERENCES SERVICOS(CODIGO_SERVICO) ON DELETE RESTRICT,
                                CONSTRAINT FK_OS_RESPONSAVEL FOREIGN KEY (CODIGO_RESPONSAVEL) REFERENCES USUARIOS(CODIGO_USUARIO) ON DELETE SET NULL,
                                CONSTRAINT FK_OS_CRIADO_POR FOREIGN KEY (CRIADO_POR) REFERENCES USUARIOS(CODIGO_USUARIO) ON DELETE RESTRICT,

                                CONSTRAINT CHK_OS_PRIORIDADE CHECK (PRIORIDADE IN ('BAIXA', 'NORMAL', 'ALTA', 'URGENTE')),
                                CONSTRAINT CHK_OS_STATUS CHECK (STATUS_OS IN ('ABERTA', 'EM_ANDAMENTO', 'AGUARDANDO_CLIENTE', 'FINALIZADA', 'CANCELADA')),
                                CONSTRAINT CHK_OS_DATAS CHECK (DATA_FINALIZACAO IS NULL OR DATA_FINALIZACAO >= DATA_ABERTURA)
);

-- ÍNDICES ESTRATÉGICOS
CREATE UNIQUE INDEX IDX_OS_NUMERO ON ORDENS_SERVICO(NUMERO_OS);
CREATE INDEX IDX_OS_CLIENTE ON ORDENS_SERVICO(CODIGO_CLIENTE);
CREATE INDEX IDX_OS_CONTRATO ON ORDENS_SERVICO(CODIGO_CONTRATO);
CREATE INDEX IDX_OS_RESPONSAVEL ON ORDENS_SERVICO(CODIGO_RESPONSAVEL) WHERE CODIGO_RESPONSAVEL IS NOT NULL;
CREATE INDEX IDX_OS_STATUS ON ORDENS_SERVICO(STATUS_OS);
CREATE INDEX IDX_OS_PRIORIDADE ON ORDENS_SERVICO(PRIORIDADE);
CREATE INDEX IDX_OS_DATA_ABERTURA ON ORDENS_SERVICO(DATA_ABERTURA DESC);
CREATE INDEX IDX_OS_DATA_LIMITE ON ORDENS_SERVICO(DATA_LIMITE) WHERE DATA_LIMITE IS NOT NULL;

-- ÍNDICE PARA KANBAN (STATUS + PRIORIDADE + DATA)
CREATE INDEX IDX_OS_KANBAN ON ORDENS_SERVICO(STATUS_OS, PRIORIDADE, DATA_ABERTURA DESC);

-- ÍNDICE PARA OS CRÍTICAS (SLA PRÓXIMO)
CREATE INDEX IDX_OS_SLA_CRITICO ON ORDENS_SERVICO(DATA_LIMITE)
    WHERE STATUS_OS IN ('ABERTA', 'EM_ANDAMENTO') AND DATA_LIMITE IS NOT NULL;

-- ÍNDICE PARA "MINHAS OS" (POR RESPONSÁVEL)
CREATE INDEX IDX_OS_RESPONSAVEL_STATUS ON ORDENS_SERVICO(CODIGO_RESPONSAVEL, STATUS_OS);

-- COMENTÁRIOS DO OS
CREATE TABLE COMENTARIOS_OS (
                                CODIGO_COMENTARIO BIGSERIAL PRIMARY KEY,
                                CODIGO_OS BIGINT NOT NULL,
                                CODIGO_USUARIO BIGINT NOT NULL,
                                COMENTARIO TEXT NOT NULL,
                                INTERNO BOOLEAN DEFAULT TRUE NOT NULL,
                                DATA_HORA_COMENTARIO TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,

                                CONSTRAINT FK_COMENTARIOS_OS FOREIGN KEY (CODIGO_OS) REFERENCES ORDENS_SERVICO(CODIGO_OS) ON DELETE CASCADE,
                                CONSTRAINT FK_COMENTARIOS_USUARIO FOREIGN KEY (CODIGO_USUARIO) REFERENCES USUARIOS(CODIGO_USUARIO) ON DELETE RESTRICT,
                                CONSTRAINT CHK_COMENTARIO_MINIMO CHECK (LENGTH(TRIM(COMENTARIO)) >= 3)
);

CREATE INDEX IDX_COMENTARIOS_OS ON COMENTARIOS_OS(CODIGO_OS, DATA_HORA_COMENTARIO DESC);
CREATE INDEX IDX_COMENTARIOS_USUARIO ON COMENTARIOS_OS(CODIGO_USUARIO);

-- HISTÓRICO DE STATUS DA OS
CREATE TABLE HISTORICO_OS_STATUS (
                                     CODIGO_HISTORICO_STATUS BIGSERIAL PRIMARY KEY,
                                     CODIGO_OS BIGINT NOT NULL,
                                     STATUS_ANTERIOR VARCHAR(30),
                                     STATUS_NOVO VARCHAR(30) NOT NULL,
                                     CODIGO_USUARIO BIGINT,
                                     DATA_HORA_MUDANCA TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                     OBSERVACAO_MUDANCA TEXT,

                                     CONSTRAINT FK_HISTORICO_OS FOREIGN KEY (CODIGO_OS) REFERENCES ORDENS_SERVICO(CODIGO_OS) ON DELETE CASCADE,
                                     CONSTRAINT FK_HISTORICO_USUARIO FOREIGN KEY (CODIGO_USUARIO) REFERENCES USUARIOS(CODIGO_USUARIO) ON DELETE SET NULL
);

CREATE INDEX IDX_HISTORICO_OS_OS ON HISTORICO_OS_STATUS(CODIGO_OS, DATA_HORA_MUDANCA DESC);

-- TRIGGER: GERAR NÚMERO DA OS
CREATE OR REPLACE FUNCTION GERAR_NUMERO_OS()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.NUMERO_OS IS NULL OR NEW.NUMERO_OS = '' THEN
        NEW.NUMERO_OS := GERAR_NUMERO_SEQUENCIAL('OS', 'SEQ_NUMERO_OS', 6);
END IF;
RETURN NEW;
END;
$$ LANGUAGE PLPGSQL;

CREATE TRIGGER TRG_OS_GERAR_NUMERO
    BEFORE INSERT ON ORDENS_SERVICO
    FOR EACH ROW
    EXECUTE FUNCTION GERAR_NUMERO_OS();

-- TRIGGER: CALCULAR DATA LIMITE COM SLA
CREATE OR REPLACE FUNCTION CALCULAR_DATA_LIMITE_OS()
RETURNS TRIGGER AS $$
DECLARE
SLA_CONTRATO INTEGER;
    SLA_SERVICO INTEGER;
    SLA_FINAL INTEGER;
BEGIN
    -- SE DATA_LIMITE JÁ FOI DEFINIDA MANUALMENTE, NÃO CALCULA
    IF NEW.DATA_LIMITE IS NOT NULL THEN
        RETURN NEW;
END IF;

    -- PEGA SLA DO CONTRATO
SELECT SLA_HORAS INTO SLA_CONTRATO FROM CONTRATOS WHERE CODIGO_CONTRATO = NEW.CODIGO_CONTRATO;

-- PEGA SLA DO SERVIÇO
SELECT SLA_HORAS INTO SLA_SERVICO FROM SERVICOS WHERE CODIGO_SERVICO = NEW.CODIGO_SERVICO;

-- PRIORIDADE: SLA DA OS > SLA DO CONTRATO > SLA DO SERVIÇO
SLA_FINAL := COALESCE(NEW.SLA_HORAS, SLA_CONTRATO, SLA_SERVICO, 24);

    -- CALCULA DATA LIMITE
    NEW.DATA_LIMITE := CALCULAR_DATA_LIMITE_SLA(NEW.DATA_ABERTURA, SLA_FINAL);

RETURN NEW;
END;
$$ LANGUAGE PLPGSQL;

CREATE TRIGGER TRG_OS_CALCULAR_DATA_LIMITE
    BEFORE INSERT ON ORDENS_SERVICO
    FOR EACH ROW
    EXECUTE FUNCTION CALCULAR_DATA_LIMITE_OS();

-- TRIGGER: REGISTRAR MUDANÇA DE STATUS
CREATE OR REPLACE FUNCTION REGISTRAR_MUDANCA_STATUS_OS()
RETURNS TRIGGER AS $$
DECLARE
CODIGO_USUARIO_ATUAL BIGINT;
BEGIN
BEGIN
        CODIGO_USUARIO_ATUAL := CURRENT_SETTING('APP.CODIGO_USUARIO', TRUE)::BIGINT;
EXCEPTION WHEN OTHERS THEN
        CODIGO_USUARIO_ATUAL := NULL;
END;

    IF (TG_OP = 'UPDATE' AND OLD.STATUS_OS != NEW.STATUS_OS) THEN
        INSERT INTO HISTORICO_OS_STATUS (CODIGO_OS, STATUS_ANTERIOR, STATUS_NOVO, CODIGO_USUARIO)
        VALUES (NEW.CODIGO_OS, OLD.STATUS_OS, NEW.STATUS_OS, CODIGO_USUARIO_ATUAL);

        -- SE FINALIZOU, REGISTRA DATA
        IF NEW.STATUS_OS = 'FINALIZADA' AND NEW.DATA_FINALIZACAO IS NULL THEN
            NEW.DATA_FINALIZACAO := CURRENT_TIMESTAMP;
END IF;
END IF;

RETURN NEW;
END;
$$ LANGUAGE PLPGSQL;

CREATE TRIGGER TRG_OS_REGISTRAR_MUDANCA_STATUS
    BEFORE UPDATE ON ORDENS_SERVICO
    FOR EACH ROW
    EXECUTE FUNCTION REGISTRAR_MUDANCA_STATUS_OS();