-- FATURAS
CREATE TABLE FATURAS (
                         CODIGO_FATURA BIGSERIAL PRIMARY KEY,
                         NUMERO_FATURA VARCHAR(20) UNIQUE NOT NULL,  -- FAT-2025-000001
                         CODIGO_CLIENTE BIGINT NOT NULL,
                         CODIGO_CONTRATO BIGINT,
                         DATA_EMISSAO DATE NOT NULL,
                         DATA_VENCIMENTO DATE NOT NULL,
                         PERIODO_INICIO DATE,
                         PERIODO_FIM DATE,
                         VALOR_TOTAL NUMERIC(10,2) NOT NULL,
                         STATUS_FATURA VARCHAR(20) DEFAULT 'PENDENTE' NOT NULL,
                         DATA_PAGAMENTO DATE,
                         FORMA_PAGAMENTO VARCHAR(50),
                         OBSERVACOES_FATURA TEXT,
                         GERADA_AUTOMATICAMENTE BOOLEAN DEFAULT FALSE NOT NULL,
                         CRIADO_EM TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
                         CRIADO_POR BIGINT NOT NULL,

                         CONSTRAINT FK_FATURAS_CLIENTE FOREIGN KEY (CODIGO_CLIENTE) REFERENCES CLIENTES(CODIGO_CLIENTE) ON DELETE RESTRICT,
                         CONSTRAINT FK_FATURAS_CONTRATO FOREIGN KEY (CODIGO_CONTRATO) REFERENCES CONTRATOS(CODIGO_CONTRATO) ON DELETE RESTRICT,
                         CONSTRAINT FK_FATURAS_CRIADO_POR FOREIGN KEY (CRIADO_POR) REFERENCES USUARIOS(CODIGO_USUARIO) ON DELETE RESTRICT,

                         CONSTRAINT CHK_FATURA_STATUS CHECK (STATUS_FATURA IN ('PENDENTE', 'PAGO', 'ATRASADO', 'CANCELADO')),
                         CONSTRAINT CHK_FATURA_VALOR_POSITIVO CHECK (VALOR_TOTAL >= 0),
                         CONSTRAINT CHK_FATURA_DATAS CHECK (DATA_VENCIMENTO >= DATA_EMISSAO),
                         CONSTRAINT CHK_FATURA_PERIODO CHECK (PERIODO_FIM IS NULL OR PERIODO_FIM >= PERIODO_INICIO),
                         CONSTRAINT CHK_FATURA_PAGAMENTO CHECK (
                             (STATUS_FATURA = 'PAGO' AND DATA_PAGAMENTO IS NOT NULL AND FORMA_PAGAMENTO IS NOT NULL) OR
                             (STATUS_FATURA != 'PAGO' AND DATA_PAGAMENTO IS NULL)
                             )
);

-- ÍNDICES
CREATE UNIQUE INDEX IDX_FATURAS_NUMERO ON FATURAS(NUMERO_FATURA);
CREATE INDEX IDX_FATURAS_CLIENTE ON FATURAS(CODIGO_CLIENTE);
CREATE INDEX IDX_FATURAS_CONTRATO ON FATURAS(CODIGO_CONTRATO);
CREATE INDEX IDX_FATURAS_STATUS ON FATURAS(STATUS_FATURA);
CREATE INDEX IDX_FATURAS_VENCIMENTO ON FATURAS(DATA_VENCIMENTO);
CREATE INDEX IDX_FATURAS_EMISSAO ON FATURAS(DATA_EMISSAO DESC);

-- ÍNDICE PARA FATURAS ATRASADAS
CREATE INDEX IDX_FATURAS_ATRASADAS
    ON FATURAS(DATA_VENCIMENTO)
    WHERE STATUS_FATURA IN ('PENDENTE', 'ATRASADO') AND DATA_VENCIMENTO IS NOT NULL;

-- ÍNDICE PARA FATURAMENTO MENSAL
CREATE INDEX IDX_FATURAS_PERIODO ON FATURAS(DATA_EMISSAO, DATA_VENCIMENTO);

-- ITENS DA FATURA
CREATE TABLE FATURA_ITENS (
                              CODIGO_ITEM BIGSERIAL PRIMARY KEY,
                              CODIGO_FATURA BIGINT NOT NULL,
                              CODIGO_SERVICO BIGINT NOT NULL,
                              DESCRICAO_ITEM VARCHAR(200),
                              QUANTIDADE INTEGER DEFAULT 1 NOT NULL,
                              VALOR_UNITARIO NUMERIC(10,2) NOT NULL,
                              VALOR_TOTAL_ITEM NUMERIC(10,2) NOT NULL,

                              CONSTRAINT FK_FATURA_ITENS_FATURA FOREIGN KEY (CODIGO_FATURA) REFERENCES FATURAS(CODIGO_FATURA) ON DELETE CASCADE,
                              CONSTRAINT FK_FATURA_ITENS_SERVICO FOREIGN KEY (CODIGO_SERVICO) REFERENCES SERVICOS(CODIGO_SERVICO) ON DELETE RESTRICT,

                              CONSTRAINT CHK_ITEM_QUANTIDADE_POSITIVA CHECK (QUANTIDADE > 0),
                              CONSTRAINT CHK_ITEM_VALOR_UNITARIO CHECK (VALOR_UNITARIO >= 0),
                              CONSTRAINT CHK_ITEM_VALOR_TOTAL CHECK (VALOR_TOTAL_ITEM = VALOR_UNITARIO * QUANTIDADE)
);

CREATE INDEX IDX_FATURA_ITENS_FATURA ON FATURA_ITENS(CODIGO_FATURA);

-- VINCULAÇÃO FATURA <-> OS
CREATE TABLE FATURA_OS (
                           CODIGO_FATURA BIGINT NOT NULL,
                           CODIGO_OS BIGINT NOT NULL,

                           PRIMARY KEY (CODIGO_FATURA, CODIGO_OS),

                           CONSTRAINT FK_FATURA_OS_FATURA FOREIGN KEY (CODIGO_FATURA) REFERENCES FATURAS(CODIGO_FATURA) ON DELETE CASCADE,
                           CONSTRAINT FK_FATURA_OS_OS FOREIGN KEY (CODIGO_OS) REFERENCES ORDENS_SERVICO(CODIGO_OS) ON DELETE CASCADE
);

CREATE INDEX IDX_FATURA_OS_FATURA ON FATURA_OS(CODIGO_FATURA);
CREATE INDEX IDX_FATURA_OS_OS ON FATURA_OS(CODIGO_OS);

-- TRIGGER: GERAR NÚMERO DA FATURA
CREATE OR REPLACE FUNCTION GERAR_NUMERO_FATURA()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.NUMERO_FATURA IS NULL OR NEW.NUMERO_FATURA = '' THEN
        NEW.NUMERO_FATURA := GERAR_NUMERO_SEQUENCIAL('FAT', 'SEQ_NUMERO_FATURA', 6);
END IF;
RETURN NEW;
END;
$$ LANGUAGE PLPGSQL;

CREATE TRIGGER TRG_FATURAS_GERAR_NUMERO
    BEFORE INSERT ON FATURAS
    FOR EACH ROW
    EXECUTE FUNCTION GERAR_NUMERO_FATURA();

-- TRIGGER: RECALCULAR VALOR TOTAL DA FATURA
CREATE OR REPLACE FUNCTION RECALCULAR_VALOR_TOTAL_FATURA()
RETURNS TRIGGER AS $$
DECLARE
NOVO_VALOR_TOTAL NUMERIC(10,2);
BEGIN
SELECT COALESCE(SUM(VALOR_TOTAL_ITEM), 0)
INTO NOVO_VALOR_TOTAL
FROM FATURA_ITENS
WHERE CODIGO_FATURA = COALESCE(NEW.CODIGO_FATURA, OLD.CODIGO_FATURA);

UPDATE FATURAS
SET VALOR_TOTAL = NOVO_VALOR_TOTAL
WHERE CODIGO_FATURA = COALESCE(NEW.CODIGO_FATURA, OLD.CODIGO_FATURA);

RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE PLPGSQL;

CREATE TRIGGER TRG_FATURA_ITENS_RECALCULAR_VALOR_INSERT
    AFTER INSERT ON FATURA_ITENS FOR EACH ROW EXECUTE FUNCTION RECALCULAR_VALOR_TOTAL_FATURA();

CREATE TRIGGER TRG_FATURA_ITENS_RECALCULAR_VALOR_UPDATE
    AFTER UPDATE ON FATURA_ITENS FOR EACH ROW EXECUTE FUNCTION RECALCULAR_VALOR_TOTAL_FATURA();

CREATE TRIGGER TRG_FATURA_ITENS_RECALCULAR_VALOR_DELETE
    AFTER DELETE ON FATURA_ITENS FOR EACH ROW EXECUTE FUNCTION RECALCULAR_VALOR_TOTAL_FATURA();

-- TRIGGER: ATUALIZAR STATUS PARA ATRASADO AUTOMATICAMENTE
-- (SERÁ EXECUTADO POR JOB DIÁRIO NO BACKEND, NÃO TRIGGER POR PERFORMANCE)