-- ÍNDICES ADICIONAIS PARA PERFORMANCE

-- ÍNDICES COMPOSTOS PARA QUERIES COMUNS
CREATE INDEX IDX_CLIENTES_STATUS_CIDADE ON CLIENTES(STATUS_CLIENTE, CIDADE) WHERE EXCLUIDO_EM IS NULL;
CREATE INDEX IDX_CONTRATOS_CLIENTE_STATUS_TIPO ON CONTRATOS(CODIGO_CLIENTE, STATUS_CONTRATO, TIPO_CONTRATO);
CREATE INDEX IDX_OS_STATUS_RESPONSAVEL_PRIORIDADE ON ORDENS_SERVICO(STATUS_OS, CODIGO_RESPONSAVEL, PRIORIDADE);
CREATE INDEX IDX_FATURAS_CLIENTE_STATUS_VENCIMENTO ON FATURAS(CODIGO_CLIENTE, STATUS_FATURA, DATA_VENCIMENTO);

-- ÍNDICES PARA RELATÓRIOS
CREATE INDEX IDX_OS_DATA_CRIACAO_MES ON ORDENS_SERVICO(CRIADO_EM);
CREATE INDEX IDX_FATURAS_EMISSAO_MES ON FATURAS(DATA_EMISSAO);

-- ÍNDICES DE TEXTO PARA BUSCA
CREATE INDEX IDX_CLIENTES_BUSCA ON CLIENTES USING GIN(TO_TSVECTOR('PORTUGUESE', RAZAO_SOCIAL || ' ' || COALESCE(NOME_FANTASIA, '')));
CREATE INDEX IDX_OS_BUSCA ON ORDENS_SERVICO USING GIN(TO_TSVECTOR('PORTUGUESE', TITULO_OS || ' ' || COALESCE(DESCRICAO_OS, '')));

-- ESTATÍSTICAS
ANALYZE USUARIOS;
ANALYZE PERFIS;
ANALYZE CLIENTES;
ANALYZE CONTRATOS;
ANALYZE SERVICOS;
ANALYZE ORDENS_SERVICO;
ANALYZE FATURAS;